config/routes.rb
Rails.application.routes.draw do
  resources :months
  root 'months#index'

end

app/models/month.rb
class Month < ActiveRecord::Base
  validates :name, presence: true
  
  def kirija_cimer
    kirija_nova.to_f/4
  end
  
  def struja_cimer
    struja.to_f / 4
  end
  
  def voda_cimer
    voda.to_f/4
  end
  
  def zgrada_cimer
    zgrada.to_f/4
  end
  
  def internet_cimer
    internet.to_f/4
  end
  
  def po_cimer
    if (kirija_cimer > 1) && (struja_cimer > 1) && (voda_cimer > 1) && (zgrada_cimer > 1) && (internet_cimer > 1)
      kirija_cimer + struja_cimer + voda_cimer + zgrada_cimer + internet_cimer
    else
      "Vnesi gi site smetki"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :set_month, only: [:show, :edit, :update, :destroy]

  # GET /months
  # GET /months.json
  def index
    @months = Month.order('created_at DESC')
  end

  # GET /months/1
  # GET /months/1.json
  def show
  end

  # GET /months/new
  def new
    @month = Month.new
  end

  # GET /months/1/edit
  def edit
  end

  # POST /months
  # POST /months.json
  def create
    @month = Month.new(month_params)

    respond_to do |format|
      if @month.save
        format.html { redirect_to root_url, notice: 'Month was successfully created.' }
        format.json { render :show, status: :created, location: @month }
      else
        format.html { render :new }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /months/1
  # PATCH/PUT /months/1.json
  def update
    respond_to do |format|
      if @month.update(month_params)
        format.html { redirect_to root_url, notice: 'Month was successfully updated.' }
        format.json { render :show, status: :ok, location: @month }
      else
        format.html { render :edit }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /months/1
  # DELETE /months/1.json
  def destroy
    @month.destroy
    respond_to do |format|
      format.html { redirect_to months_url, notice: 'Month was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_month
      @month = Month.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def month_params
      params.require(:month).permit(:name, :kirija, :struja, :voda, :internet, :zgrada, :petar_kirija, :petar_struja, :petar_voda, :petar_zgrada, :petar_internet, :brane_kirija, :brane_struja, :brane_voda, :brane_zgrada, :brane_internet, :dmz_kirija, :dmz_struja, :dmz_voda, :dmz_zgrada, :dmz_internet, :gare_kirija, :gare_struja, :gare_voda, :gare_zgrada, :gare_internet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ROOMMATES - By Petar Hakerman" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ROOMMATES - By Petar Hakerman", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Kreiraj Mesec", new_month_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br /><br />
      <footer>
        <p>Cimerite od Partizanski Odredi !!!! &copy; Created by Petar Hakerman !!!! </p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/months/_form.html.erb
<%= form_for(@month) do |f| %>
  <% if @month.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@month.errors.count, "error") %> prohibited this month from being saved:</h2>

      <ul>
      <% @month.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kirija_nova %><br>
    <%= f.number_field :kirija_nova %>
  </div>
  <div class="field">
    <%= f.label :struja %><br>
    <%= f.number_field :struja %>
  </div>
  <div class="field">
    <%= f.label :voda %><br>
    <%= f.number_field :voda %>
  </div>
  <div class="field">
    <%= f.label :internet %><br>
    <%= f.number_field :internet %>
  </div>
  <div class="field">
    <%= f.label :zgrada %><br>
    <%= f.number_field :zgrada %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/months/edit.html.erb
<h1>Editing Month</h1>

<%= form_for(@month) do |f| %>
  <% if @month.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@month.errors.count, "error") %> prohibited this month from being saved:</h2>

      <ul>
      <% @month.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kirija_nova %><br>
    <%= f.number_field :kirija_nova %>
  </div>
  <div class="field">
    <%= f.label :struja %><br>
    <%= f.number_field :struja %>
  </div>
  <div class="field">
    <%= f.label :voda %><br>
    <%= f.number_field :voda %>
  </div>
  <div class="field">
    <%= f.label :internet %><br>
    <%= f.number_field :internet %>
  </div>
  <div class="field">
    <%= f.label :zgrada %><br>
    <%= f.number_field :zgrada %>
  </div>
  
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Smetki</th>
      <th>Petar</th>
      <th>Brane</th>
      <th>Dmz</th>
      <th>Gare</th>
    </tr>
  </thead>

  <tbody>
      
    <tr>
      <td>Kirija</td>
      <td><%= f.check_box :petar_kirija %></td>
      <td><%= f.check_box :brane_kirija %></td>
      <td><%= f.check_box :dmz_kirija %></td>
      <td><%= f.check_box :gare_kirija %></td>
    </tr>
    
    <tr>
      <td>Struja</td>
      <td><%= f.check_box :petar_struja %></td>
      <td><%= f.check_box :brane_struja %></td>
      <td><%= f.check_box :dmz_struja %></td>
      <td><%= f.check_box :gare_struja %></td>
    </tr>
    
    <tr>
      <td>Voda</td>
      <td><%= f.check_box :petar_voda %></td>
      <td><%= f.check_box :brane_voda %></td>
      <td><%= f.check_box :dmz_voda %></td>
      <td><%= f.check_box :gare_voda %></td>
    </tr>
    
    <tr>
      <td>Zgrada</td>
      <td><%= f.check_box :petar_zgrada %></td>
      <td><%= f.check_box :brane_zgrada %></td>
      <td><%= f.check_box :dmz_zgrada %></td>
      <td><%= f.check_box :gare_zgrada %></td>
    </tr>
    
    <tr>
      <td>Internet</td>
      <td><%= f.check_box :petar_internet %></td>
      <td><%= f.check_box :brane_internet %></td>
      <td><%= f.check_box :dmz_internet %></td>
      <td><%= f.check_box :gare_internet %></td>
    </tr>
    
  </tbody>
</table>

  
  <div class="actions">
    <%= f.submit :class => "btn btn-success"  %>
  </div>
<% end %>


<%= link_to 'Doma', root_path, class: "btn btn-info" %>

app/views/months/index.html.erb
<h1>Listing Months</h1>
<% @months.each do |month| %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Petar</th>
      <th>Brane</th>
      <th>Dmz</th>
      <th>Gare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <p class="lead">Po cimer za mesec <%= month.name %>: <%= month.po_cimer %></p>
      <p>Kirija: <%= month.kirija_cimer %> | Struja: <%= month.struja_cimer %> | Voda: <%= month.voda_cimer %> | Zgrada: <%= month.zgrada_cimer %> | Internet: <%= month.internet_cimer %></p>
      <tr>
        <td><strong><%= month.name %></strong></td>
      </tr>
      <tr>
        <td>Kirija: <%= month.kirija_nova %></td>
        <td>
          <% if month.petar_kirija %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.brane_kirija %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.dmz_kirija %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.gare_kirija %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Struja: <%= month.struja %></td>
        <td>
          <% if month.petar_struja %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.brane_struja %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.dmz_struja %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.gare_struja %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Voda: <%= month.voda %></td>
        <td>
          <% if month.petar_voda %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.brane_voda %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.dmz_voda %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.gare_voda %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
      </tr>
      <tr>  
        <td>Internet: <%= month.internet %></td>
        <td>
          <% if month.petar_internet %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.brane_internet %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.dmz_internet %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.gare_internet %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        
      </tr>
      <tr>
        <td>Zgrada: <%= month.zgrada %></td>
        <td>
          <% if month.petar_zgrada %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.brane_zgrada %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.dmz_zgrada %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
        <td>
          <% if month.gare_zgrada %>
            <p class="da">plateno</p>
          <% else %>
            <p class="ne">nema</p>
          <% end %>
        </td>
      
       
        <td><%= link_to 'Editiraj !', edit_month_path(month), class: "btn btn-xs btn-info" %></td>
        <td><%= link_to 'Izbrishi mesec', month, method: :delete, data: { confirm: 'Sigurno sakash da go izbrishish mesecot ? Hakerman che ti vika !!!!!!' }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    
  </tbody>
</table><br />
<% end %>
<br>

<%= link_to 'New Month', new_month_path, class: "btn btn-success" %>

app/views/months/new.html.erb
<h1>New Month</h1>

<%= render 'form' %>

<%= link_to 'Back', months_path %>

app/views/months/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @month.name %>
</p>

<p>
  <strong>Kirija:</strong>
  <%= @month.kirija %>
</p>

<p>
  <strong>Struja:</strong>
  <%= @month.struja %>
</p>

<p>
  <strong>Voda:</strong>
  <%= @month.voda %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @month.internet %>
</p>

<p>
  <strong>Zgrada:</strong>
  <%= @month.zgrada %>
</p>

<p>
  <strong>Petar kirija:</strong>
  <%= @month.petar_kirija %>
</p>

<p>
  <strong>Petar struja:</strong>
  <%= @month.petar_struja %>
</p>

<p>
  <strong>Petar voda:</strong>
  <%= @month.petar_voda %>
</p>

<p>
  <strong>Petar zgrada:</strong>
  <%= @month.petar_zgrada %>
</p>

<p>
  <strong>Petar internet:</strong>
  <%= @month.petar_internet %>
</p>

<p>
  <strong>Brane kirija:</strong>
  <%= @month.brane_kirija %>
</p>

<p>
  <strong>Brane struja:</strong>
  <%= @month.brane_struja %>
</p>

<p>
  <strong>Brane voda:</strong>
  <%= @month.brane_voda %>
</p>

<p>
  <strong>Brane zgrada:</strong>
  <%= @month.brane_zgrada %>
</p>

<p>
  <strong>Brane internet:</strong>
  <%= @month.brane_internet %>
</p>

<p>
  <strong>Dmz kirija:</strong>
  <%= @month.dmz_kirija %>
</p>

<p>
  <strong>Dmz struja:</strong>
  <%= @month.dmz_struja %>
</p>

<p>
  <strong>Dmz voda:</strong>
  <%= @month.dmz_voda %>
</p>

<p>
  <strong>Dmz zgrada:</strong>
  <%= @month.dmz_zgrada %>
</p>

<p>
  <strong>Dmz internet:</strong>
  <%= @month.dmz_internet %>
</p>

<p>
  <strong>Gare kirija:</strong>
  <%= @month.gare_kirija %>
</p>

<p>
  <strong>Gare struja:</strong>
  <%= @month.gare_struja %>
</p>

<p>
  <strong>Gare voda:</strong>
  <%= @month.gare_voda %>
</p>

<p>
  <strong>Gare zgrada:</strong>
  <%= @month.gare_zgrada %>
</p>

<p>
  <strong>Gare internet:</strong>
  <%= @month.gare_internet %>
</p>

<%= link_to 'Edit', edit_month_path(@month) %> |
<%= link_to 'Back', months_path %>